name: ServerManager
version: Alpha-1.0
authors: [NeoOSky, _Anto, MembersOfSkriptMC] 
main: eu.dev.servermanager.spigot.Main 
website: https://discord.gg/FX5sQPr
commands:
  servermanager:
    aliases: sm
  op:
  clear:
    description: clear inventory from a player
