# _______  _______  _______           _______  _______  _______  _______  _        _______  _______  _______  _______
#(  ____ \(  ____ \(  ____ )|\     /|(  ____ \(  ____ )(       )(  ___  )( (    /|(  ___  )(  ____ \(  ____ \(  ____ )
#| (    \/| (    \/| (    )|| )   ( || (    \/| (    )|| () () || (   ) ||  \  ( || (   ) || (    \/| (    \/| (    )|
#| (_____ | (__    | (____)|| |   | || (__    | (____)|| || || || (___) ||   \ | || (___) || |      | (__    | (____)|
#(_____  )|  __)   |     __)( (   ) )|  __)   |     __)| |(_)| ||  ___  || (\ \) ||  ___  || | ____ |  __)   |     __)
#      ) || (      | (\ (    \ \_/ / | (      | (\ (   | |   | || (   ) || | \   || (   ) || | \_  )| (      | (\ (
#/\____) || (____/\| ) \ \__  \   /  | (____/\| ) \ \__| )   ( || )   ( || )  \  || )   ( || (___) || (____/\| ) \ \__
#\_______)(_______/|/   \__/   \_/   (_______/|/   \__/|/     \||/     \||/    )_)|/     \|(_______)(_______/|/   \__/
#

# If you don't want to use a functionality of ServerManager, set the Event to false or set text to "dont use".
# We are free french developers. You help us when you rate this plugin ! You can also send a comment for ask to add new functionality.
# If you found a bug, write a comment on spigot and we will correct it quickly.
# If you really want to help us, use command "/servermanager pub" for broadcast a little pub.

PluginPriority: HIGHEST


########################################
#--------------------------------------#
#               Messages               #
#--------------------------------------#
########################################

# use fr_FR, en_EN or custom_CUSTOM
Lang: 'fr_FR'


fr_FR:
  Prefix:
    prefix: '&c&lServerManager&8 » '
    prefix_maintenance: '&cMaintenance&8 » '
    prefix_chat: '&cChatManager&8 » '
    prefix_error: '&cErreur&8 » '
    prefix_sucess: '&aSuccès&8 » '
    prefix_moderation: '&6[Modération] '
    prefix_administration: '&c[Admin] '
    Mod:
      prefix_warn: '&cAvertissement&8 » '
      prefix_ban: '&cBan&8 » '
      prefix_tempban: '&cTemp-Ban&8 » '
      prefix_mute: '&cMute&8 » '
      prefix_tempmute: '&cTemp-Mute&8 » '
  Messages:
    noperm: 'Vous n''avez pas la permission requise !'
    arg_player: 'Merci de spécifier un joueur.'
    arg_text: 'Merci de spécifier un argument.'
    arg_notonline: '%target% n''est pas connecté.'
    Mod:
      kick_header: '&8&m---------------&8(&b ServerManager&8 )&8&m----------------'
      kick_footer: '&8&m----------------------------------------------'
      




en_EN:
  prefix: '&dEnglish'