name: ServerManager
version: Alpha-1.0
authors: [NeoOSky, _Anto, Palamix, MembersOfSkriptMC]
main: eu.servermanager.dev.spigot.Main
website: https://discord.gg/FX5sQPr
commands:
  servermanager:
    aliases: sm
  clear:
    description: clear inventory from a player
  maintenance:
    description: manage the maintenance of the server